# Generated by Django 5.2 on 2025-04-16 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo_html", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descricoes",
                        to="my_portfolio.evento",
                    ),
                ),
            ],
        ),
    ]
