# Generated by Django 5.2 on 2025-04-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0002_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="descricao",
            new_name="resumo",
        ),
        migrations.RemoveField(
            model_name="descricao",
            name="evento",
        ),
        migrations.AddField(
            model_name="descricao",
            name="evento_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_portfolio.evento",
            ),
        ),
        migrations.AlterField(
            model_name="descricao",
            name="conteudo_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="descricao",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
