# Generated by Django 5.2 on 2025-04-16 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0003_rename_descricao_evento_resumo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="descricao",
            name="slug",
        ),
    ]
