# Generated by Django 5.2 on 2025-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0004_remove_descricao_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={"ordering": ["-data_inicio"]},
        ),
        migrations.RemoveField(
            model_name="evento",
            name="concluido",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="ordem",
        ),
        migrations.AddField(
            model_name="evento",
            name="data_conclusao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
