# Generated by Django 5.2 on 2025-04-18 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0005_alter_evento_options_remove_evento_concluido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="ano",
        ),
    ]
